# Generated by Django 4.2.6 on 2023-11-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=200)),
                ('station_name', models.CharField(max_length=200)),
            ],
        ),
    ]
