# Generated by Django 4.2.6 on 2023-11-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq_soft', '0002_stations_lat_stations_lon_stations_station_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_gender', models.CharField(max_length=5)),
                ('user_birthdate', models.DateField(blank=True, null=True)),
                ('user_residence', models.CharField(max_length=5)),
                ('ride_date', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('station_start', models.CharField(max_length=200)),
                ('station_end', models.CharField(max_length=200)),
                ('ride_duration', models.FloatField(blank=True, null=True)),
                ('ride_late', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
